version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn backend.wsgi:application -w 4 -b 0.0.0.0:8000" 
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - mysql
    env_file:
      - .env


  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql 


  nginx:
    image: nginx:latest
    volumes:
      - ./media:/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    depends_on:
      - web

volumes:
  mysql_data:

