# Generated by Django 4.2.7 on 2023-11-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FancyPet", "0002_user_atcnum_user_fans_user_follow"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("openid", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("image", models.CharField(max_length=255)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("like", models.IntegerField(default=0)),
                ("comment", models.IntegerField(default=0)),
                ("read", models.IntegerField(default=0)),
            ],
        ),
    ]
