# Generated by Django 4.2.7 on 2023-11-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FancyPet", "0004_remove_article_image_articleimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="images",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ArticleImage",
        ),
    ]
