# Generated by Django 4.2.7 on 2023-11-10 09:09

import FancyPet.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FancyPet", "0005_article_images_delete_articleimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="user/logo.png",
                max_length=255,
            ),
        ),
    ]
