# Generated by Django 4.2.7 on 2023-11-10 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FancyPet", "0006_remove_user_avatar_user_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="image",
            new_name="avatar",
        ),
    ]
