# Generated by Django 4.2.7 on 2023-11-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FancyPet", "0007_rename_image_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(max_length=255),
        ),
    ]
