# Generated by Django 4.2.7 on 2023-11-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
                ('images', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
