# Generated by Django 4.2.7 on 2023-11-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0010_count_article_articleid_petspace_petspaceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likedArticles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
