# Generated by Django 4.2.7 on 2023-11-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0011_user_likedarticles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='count',
            name='CommentNum',
            field=models.IntegerField(default=0),
        ),
    ]
