# Generated by Django 4.2.7 on 2023-11-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0013_comment_remove_article_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='share',
            field=models.IntegerField(default=0),
        ),
    ]
