# Generated by Django 4.2.7 on 2023-11-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0016_alter_article_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='petspace',
            name='gender',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='petspace',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petspace',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
