# Generated by Django 4.2.7 on 2023-11-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0017_petspace_gender_petspace_month_petspace_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petspace',
            name='month',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='petspace',
            name='year',
            field=models.CharField(default='', max_length=255),
        ),
    ]
