# Generated by Django 4.2.7 on 2023-11-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0019_user_likedcomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('ActivityID', models.CharField(default='0', max_length=255)),
                ('PetSpaceID', models.CharField(default='0', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='count',
            name='ActivityNum',
            field=models.IntegerField(default=1),
        ),
    ]
