# Generated by Django 4.2.7 on 2023-11-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0020_activity_count_activitynum'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.CharField(default='', max_length=255),
        ),
    ]
