# Generated by Django 4.2.7 on 2023-11-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0021_activity_address_activity_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='img',
            field=models.CharField(default='', max_length=255),
        ),
    ]
