# Generated by Django 4.2.7 on 2023-11-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0022_activity_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='petspace',
            name='imageNum',
            field=models.IntegerField(default=0),
        ),
    ]
