# Generated by Django 4.2.7 on 2023-11-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0023_petspace_imagenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='UserNum',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='UserID',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
