# Generated by Django 4.2.7 on 2023-11-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0024_count_usernum_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followUsers',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
