# Generated by Django 4.2.7 on 2023-11-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0026_alter_user_followusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followUsers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
