# Generated by Django 4.2.7 on 2023-12-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0027_alter_user_followusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255)),
                ('MessageID', models.CharField(default='0', max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='count',
            name='MessageNum',
            field=models.IntegerField(default=1),
        ),
    ]
