# Generated by Django 4.2.7 on 2023-12-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0030_message_petspaceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='UserID',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
