# Generated by Django 4.2.7 on 2023-12-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0032_rename_petspaceid_message_petspaceid1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ActivityId',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
