# Generated by Django 4.2.7 on 2023-12-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0033_message_activityid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ActivityId',
            new_name='ActivityID',
        ),
    ]
