# Generated by Django 4.2.7 on 2023-12-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0034_rename_activityid_message_activityid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='UserID',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
