# Generated by Django 4.2.7 on 2023-12-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0035_article_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='petspace',
            name='healthRecord',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
