# Generated by Django 4.2.7 on 2023-12-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0038_article_petspaceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
