# Generated by Django 4.2.7 on 2023-12-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0039_user_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subzone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='zone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
