# Generated by Django 4.2.7 on 2023-12-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0040_article_subzone_article_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='petspace',
            name='public',
            field=models.IntegerField(default=0),
        ),
    ]
