# Generated by Django 4.2.7 on 2023-12-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0042_petspace_shareusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followPets',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
