# Generated by Django 4.2.7 on 2023-12-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0043_user_followpets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255),
        ),
    ]
