# Generated by Django 4.2.7 on 2023-12-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0044_alter_article_content_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
