# Generated by Django 4.2.7 on 2023-12-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0045_alter_activity_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
