# Generated by Django 4.2.7 on 2023-12-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0048_video_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='petspace',
            name='birthday',
            field=models.CharField(default='2023-01-01', max_length=255),
        ),
    ]
