# Generated by Django 4.2.7 on 2023-12-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FancyPet', '0050_article_combined_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='combined_score',
        ),
    ]
